/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

import controller.orderController;
import controller.productController;

/**
 *
 * @author REDMIBOOK
 */
public class mainpos extends javax.swing.JFrame {
    String orderId = "";

    private Map<String, Integer> productMap = new HashMap<>();

    /**
     * Creates new form mainpos
     * @throws ClassNotFoundException
     * @throws SQLException
     */
    public mainpos(int userid) throws ClassNotFoundException, SQLException {
        initComponents(userid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @throws ClassNotFoundException
     * @throws SQLException
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(int userid) throws ClassNotFoundException, SQLException {

        SideBar = new javax.swing.JPanel();
        Qty = new javax.swing.JTextField();
        TambahBeli = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        KembaliDash = new javax.swing.JButton();
        ProdukItem = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BeliPanel = new javax.swing.JPanel();
        InputUang = new javax.swing.JTextField();
        Edit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        Total = new javax.swing.JLabel();
        Bayar = new javax.swing.JLabel();
        Kembalian = new javax.swing.JLabel();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SideBar.setBackground(new java.awt.Color(204, 51, 0));

        Qty.setBackground(new java.awt.Color(153, 51, 0));
        Qty.setForeground(new java.awt.Color(255, 255, 255));
        Qty.setToolTipText("Masukan Quantity (Jumlah Barang Yang Dibeli)");


        TambahBeli.setBackground(new java.awt.Color(255, 153, 153));
        TambahBeli.setText("Tambah");
        TambahBeli.addActionListener(new java.awt.event.ActionListener() {

            @Override
            public void actionPerformed(ActionEvent arg0) {
                // TODO Auto-generated method stub
                try {
                    TambahOrder(userid);
                } catch (ClassNotFoundException | SQLException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }


        });


        Edit.setBackground(new java.awt.Color(255, 153, 153));
        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    EditActionPerformed(evt, userid);
                } catch (NumberFormatException | ClassNotFoundException | SQLException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama Produk :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Quantity :");

        KembaliDash.setBackground(new java.awt.Color(255, 153, 153));
        KembaliDash.setText("Kembali");
        KembaliDash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    KembaliDashActionPerformed(evt, userid);
                } catch (ClassNotFoundException | SQLException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });

        ProdukItem.setBackground(new java.awt.Color(153, 51, 0));
        ProdukItem.setForeground(new java.awt.Color(255, 255, 255));
        // ProdukItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        dataComboBox();



        javax.swing.GroupLayout SideBarLayout = new javax.swing.GroupLayout(SideBar);
        SideBar.setLayout(SideBarLayout);
        SideBarLayout.setHorizontalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SideBarLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(SideBarLayout.createSequentialGroup()
                                .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TambahBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Qty)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ProdukItem, 0, 193, Short.MAX_VALUE))))
                    .addGroup(SideBarLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(KembaliDash)))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        SideBarLayout.setVerticalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProdukItem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Qty, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(TambahBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addComponent(KembaliDash)
                .addContainerGap(288, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 255, 51));

        jLabel1.setBackground(new java.awt.Color(0, 255, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 0));
        jLabel1.setText("SUII TOKO [POS]");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        BeliPanel.setBackground(new java.awt.Color(0, 51, 102));
        BeliPanel.setForeground(new java.awt.Color(255, 255, 255));

        InputUang.setToolTipText("Masukan Uang Pembeli Disini...");


        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total :");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bayar :");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kembalian :");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "OrderID", "Nama Product", "Quantity Product","Total Harga", "Admin Kasir", "Tanggal Order", "Order Status"
            }
        ));
    jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
        @Override
        public void valueChanged(ListSelectionEvent event) {
            if (!event.getValueIsAdjusting()) {
                int selectedRow = jTable1.getSelectedRow();

                if (selectedRow != -1) {
                    orderId = jTable1.getValueAt(selectedRow, 0).toString();
                    String productName = jTable1.getValueAt(selectedRow, 1).toString();
                    String quantity = jTable1.getValueAt(selectedRow, 2).toString();

                    ProdukItem.setSelectedItem(productName);
                    Qty.setText(quantity);
                }
            }
        }
    });
        loadData(userid);
        jScrollPane1.setViewportView(jTable1);

        jButton3.setBackground(new java.awt.Color(255, 102, 102));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Bayar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    BayarEvent(evt, userid);
                } catch (ClassNotFoundException | SQLException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }


        });

        Total.setForeground(new java.awt.Color(255, 255, 255));
        Total.setText(orderController.totalPembelian(userid));

        Bayar.setForeground(new java.awt.Color(255, 255, 255));
        // Bayar.setText(InputUang.getText());

        Kembalian.setForeground(new java.awt.Color(255, 255, 255));
        // Kembalian.setText("0");

        javax.swing.GroupLayout BeliPanelLayout = new javax.swing.GroupLayout(BeliPanel);
        BeliPanel.setLayout(BeliPanelLayout);
        BeliPanelLayout.setHorizontalGroup(
            BeliPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BeliPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(BeliPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BeliPanelLayout.createSequentialGroup()
                        .addComponent(InputUang, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BeliPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        BeliPanelLayout.setVerticalGroup(
            BeliPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BeliPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(BeliPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputUang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(Total)
                    .addComponent(Bayar)
                    .addComponent(Kembalian))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(SideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(BeliPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BeliPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadData(int userId) throws ClassNotFoundException {
        List<models.Orders> orderList = orderController.GetAllOrderData(userId);
    
        // Clear existing rows from the table
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
    

        for (models.Orders orders : orderList) {
            Object[] rowData = {orders.getOrderId(),orders.getProductName(), orders.getOrderQty(), orders.getTotal(),orders.getUserName(), orders.getOrderDate(), orders.getOrderSelesai()};
            model.addRow(rowData);
        }
    }
    private void TambahOrder(int userid) throws ClassNotFoundException, SQLException {
        String selectedProduct = ProdukItem.getSelectedItem().toString();
        int selectedProductId = productMap.get(selectedProduct);
        String jum = Qty.getText();
        int orderQty = Integer.parseInt(jum);
        
        dispose();
        this.setVisible(false);
        orderController.insertOrderData(selectedProductId, orderQty, userid);
        mainpos pos = new mainpos(userid);
        pos.setVisible(true);
        pos.setTitle("SUII MAIN POS");

    }

    private void BayarEvent(java.awt.event.ActionEvent evt , int userid) throws ClassNotFoundException, SQLException {
 
        String totalAmountStr = Total.getText();
        double totalAmount = Double.parseDouble(totalAmountStr);

        String inputUangValue = InputUang.getText();
        double amountPaid = Double.parseDouble(inputUangValue);

        if (amountPaid < totalAmount) {

            JOptionPane.showMessageDialog(jButton3, "Uang Kurang");
        } else {
            double kembalianValue = amountPaid - totalAmount;
            orderController.bayarOrder(userid);

            Bayar.setText(String.valueOf(amountPaid));
            Kembalian.setText(String.valueOf(kembalianValue));
            clearTable();
        }


    }

    private void dataComboBox() {
        try {
            // Get product data from the controller
            List<models.Product> productList = productController.GetAllproductData();
    
            ProdukItem.removeAllItems();
    
            for (models.Product product : productList) {
                ProdukItem.addItem(product.getProductName());
                productMap.put(product.getProductName(), product.getProductId());
            }
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
    }
    private void clearTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        model.setColumnCount(0);
    }

    private void EditActionPerformed(java.awt.event.ActionEvent evt, int userId) throws NumberFormatException, ClassNotFoundException, SQLException {                                     
        // TODO add your handling code here:
        String selectedProduct = ProdukItem.getSelectedItem().toString();
        int selectedProductId = productMap.get(selectedProduct);
        String jum = Qty.getText();
        int orderQty = Integer.parseInt(jum);


        dispose();
        this.setVisible(false);
        orderController.updateOrderData(Integer.parseInt(orderId),selectedProductId, orderQty, userId);
        mainpos pos = new mainpos(userId);
        pos.setVisible(true);
        pos.setTitle("SUII MAIN POS");
    } 

    private void KembaliDashActionPerformed(java.awt.event.ActionEvent evt, int userid) throws ClassNotFoundException, SQLException {//GEN-FIRST:event_KembaliDashActionPerformed
        // TODO add your handling code here:
        dispose();
        this.setVisible(false);
        dashboard dash = new dashboard(userid);
        dash.setVisible(true);
        dash.setTitle("SUI DASHBOARD");
    }//GEN-LAST:event_KembaliDashActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainpos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainpos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainpos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainpos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        // java.awt.EventQueue.invokeLater(new Runnable() {
        //     public void run() {
        //         new mainpos().setVisible(true);
        //     }
        // });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bayar;
    private javax.swing.JPanel BeliPanel;
    private javax.swing.JTextField InputUang;
    private javax.swing.JButton KembaliDash;
    private javax.swing.JLabel Kembalian;
    private javax.swing.JComboBox<String> ProdukItem;
    private javax.swing.JTextField Qty;
    private javax.swing.JPanel SideBar;
    private javax.swing.JButton TambahBeli;
    private javax.swing.JLabel Total;
    private javax.swing.JButton Edit;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
